### PR TITLE
fix: push non-versioned tags

### PR DESCRIPTION
**Pull request by catthehacker**

### CODE REVIEW

**Comment by bl-ue** [comment]
Unrelated: is `[skip ci]` a GitHub thing or did you write code to support it?

**Comment by catthehacker** [comment]
Most CI/CD support that behaviour
`[skip ci]` would usually skip whatever CI you have while `[skip actions]` will skip GitHub Actions, but would still run Azure DevOps Pipelines and Travis CI
https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build
https://docs.github.com/en/actions/guides/about-continuous-integration#skipping-workflow-runs
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#skipping-ci-for-individual-commits

**Comment by catthehacker** [comment]
it's still broken, but I'm fixing it, *I love environment variables on Linux*

**Comment by dustinfarris** [comment]
do non-versioned tags need to be pushed again?

I'm getting 

```
[Cypress Tests/cypress-run] 🚀  Start image=catthehacker/ubuntu:full-latest
Error: Error response from daemon: manifest for catthehacker/ubuntu:full-latest not found: manifest unknown: manifest unknown
```

**Comment by catthehacker** [comment]
`full-*` is not updated on DockerHub, it's only available on `ghcr.io` currently @dustinfarris

**Pull request merged**
